services:
  spark-client:
    image: bitnami/spark:3.5
    container_name: de_spark_practice_client
    working_dir: /app
    volumes:
      - ./:/app
    command: ["bash", "-lc", "sleep infinity"]
    ports:
      - "4040:4040"

